##### PREFIX #####
unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

# Horizontal split (left / right)
bind | split-window -h -c "#{pane_current_path}"

# Vertical split (top / bottom)
bind _ split-window -v -c "#{pane_current_path}"

##### PANE RESIZE (CTRL + HJKL) #####
bind -r H resize-pane -L 2
bind -r L resize-pane -R 2
bind -r K resize-pane -U 2
bind -r J resize-pane -D 2

##### PANE NAVIGATION (PREFIX + HJKL) #####
bind h select-pane -L
bind l select-pane -R
bind k select-pane -U
bind j select-pane -D

bind a last-window

##### COPY MODE (VI) #####
#set-window-option -g mode-keys vi
set -g mode-keys vi
bind -T copy-mode-vi v send -X begin-selection
bind -T copy-mode-vi V send -X select-line
# copy WITHOUT exiting (important!)
bind -T copy-mode-vi y send -X copy-selection
# quit copy mode manually
bind -T copy-mode-vi q send -X cancel
set -g status-position top
set -g mouse on
set -g history-limit 100000
set -sg escape-time -0

unbind -T copy-mode-vi MouseDragEnd1Pane
bind -T copy-mode-vi MouseDragEnd1Pane send -X copy-selection

##### Dark Minimal
# set -g status-style bg=#1f2335,fg=#c0caf5
#
# set -g status-left "#[fg=#7aa2f7,bold] #S "
# set -g status-right "#[fg=#a9b1d6]%Y-%m-%d #[fg=#7dcfff]%H:%M "
#
# set -g window-status-format " #[fg=#a9b1d6]#I:#W "
# set -g window-status-current-format "#[bg=#7aa2f7,fg=#1f2335,bold] #I:#W "

##### Powerline 
set -g status-style bg=#282c34,fg=#abb2bf

set -g status-left-length 50
set -g status-left "#[bg=#61afef,fg=#282c34,bold] #S #[bg=#282c34,fg=#61afef]"

set -g status-right "#[bg=#282c34,fg=#98c379]#[bg=#98c379,fg=#282c34] %H:%M #[bg=#e06c75,fg=#282c34] %Y-%m-%d "

set -g window-status-current-format "#[bg=#e5c07b,fg=#282c34,bold] #I:#W "
set -g window-status-format " #[fg=#abb2bf]#I:#W "

##### Bonus feature
set -g status-interval 1
set -g status-justify centre
set -g pane-border-style fg=#444444
set -g pane-active-border-style fg=#7aa2f7


